# Generated by Django 2.2 on 2024-06-18 04:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weather',
            old_name='city_name',
            new_name='City_name',
        ),
        migrations.RenameField(
            model_name='weather',
            old_name='temperature',
            new_name='Temperature',
        ),
        migrations.AddField(
            model_name='weather',
            name='Description',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
