# Generated by Django 2.2 on 2024-06-18 04:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0002_auto_20240618_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='Date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
