# Generated by Django 2.2 on 2024-06-18 07:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0003_weather_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='Emailid',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
